### ISSUE TITLE
Have you tried Dilated convs? 

### ISSUE THREAD

**Issue by artvandelay** [Kaixhin/FCN-semantic-segmentation#1]
Source:
https://github.com/fyu/dilation
P. Wang et al., “Understanding Convolution for Semantic Segmentation,” arXiv [cs.CV], 27-Feb-2017.

**Comment by Kaixhin** [comment]
Actually I've been trying [Dilated Residual Networks](http://vladlen.info/publications/dilated-residual-networks/) but haven't been able to replicate the results so far. The author, Fisher, said that he will make his code available at some point though. In the meantime I might have a look at this, thanks.

**Comment by Kaixhin** [comment]
Closing as the author of the above has [released his code](https://github.com/fyu/drn), and it includes training for semantic segmentation. I'll keep this with a more standard FCN architecture so there's more diversity in example code. It appears that he used a DRN pretrained on ImageNet for segmentation, hence why I couldn't replicate his results starting from scratch.
