### ISSUE TITLE
Implementation and Test

### ISSUE THREAD

**Issue by mellou01** [Kaixhin/FCN-semantic-segmentation#10]
Thank you for providing the code but it seems not giving good results with cityscapes and also with my own data set. The mean IOU I am getting is around 0,2% can you explain this?

**Comment by Kaixhin** [comment]
This repo is just to provide a minimal example for semantic segmentation (a whole pipeline in < 300 LoC), but it is fairly basic and is not particularly well tuned so you would need to do a lot of tuning, or even look at more advanced repos if you want good performance.
