### ISSUE TITLE
RuntimeError: CUDA out of memory

### ISSUE THREAD

**Issue by jouming** [Kaixhin/FCN-semantic-segmentation#11]
Hi Kaixhin. The following error occurred when I ran the code: 
RuntimeError: CUDA out of memory. Tried to allocate 16.00 MiB (GPU 0; 4.00 GiB total capacity; 1.40 GiB already allocated; 0 bytes free; 16.43 MiB cached)

My computer's graphics card has only 4GB of memory, and I have changed the size of batch to1.
I would really appreciate it if you could give me some advice.

**Comment by Kaixhin** [comment]
Segmentation requires a lot of memory, so you may not be able to use this code successfully. The other thing you can reduce is `--crop-size` from 512 to something like 128, which will reduce memory requirements by 16x.

**Comment by jouming** [comment]
> Segmentation requires a lot of memory, so you may not be able to use this code successfully. The other thing you can reduce is `--crop-size` from 512 to something like 128, which will reduce memory requirements by 16x.

Thank you  for you reply. I reduced the value of `--crop-size`, but it has the same error.

**Comment by Kaixhin** [comment]
I'm surprised `--batch-size 1 --crop-size 128` still gives you CUDA memory issues, but you can try reducing the crop size even further (say `16`) just to test if you get the same error (though at this point the input might be too small for the network). You could also try changing the optimiser from `RMSprop` to `SGD`.

In the README it does mention that the default configuration uses about 10GB of memory, so if you are looking to do segmentation with a smaller GPU you are better off finding another repo that implements more efficient models.

**Comment by jouming** [comment]
> I'm surprised `--batch-size 1 --crop-size 128` still gives you CUDA memory issues, but you can try reducing the crop size even further (say `16`) just to test if you get the same error (though at this point the input might be too small for the network). You could also try changing the optimiser from `RMSprop` to `SGD`.
> 
> In the README it does mention that the default configuration uses about 10GB of memory, so if you are looking to do segmentation with a smaller GPU you are better off finding another repo that implements more efficient models.

Kaixhin, Thank you for your patient reply. Although I reduced the crop size to 16, it still doesn't work. I'll find another models. Thanks!
