### ISSUE TITLE
billinear interpolation filters

### ISSUE THREAD

**Issue by amiltonwong** [Kaixhin/FCN-semantic-segmentation#3]
Hi, @Kaixhin ,

Have you appended the billinear interpolation filters in your fcn implementation? I cannot found this layer in your code. Is that the reason for lower performance ?

**Comment by Kaixhin** [comment]
It is true that sometimes people have reported better results by replacing transposed convolutions with bilinear filtering. I just tried this, replacing all of my transposed convolutions with bilinear upsampling + normal convolutions, but this does not seem to make a change to previous results that reached 30% IoU quickly and saturated at 40% IoU (graph below).

![ious](https://user-images.githubusercontent.com/991891/28757249-3bbdbaea-7576-11e7-9e98-473cf1adb956.png)
