### ISSUE TITLE
RuntimeError: The expanded size of the tensor (256) must match the existing size (512) at non-singleton dimension 1

### ISSUE THREAD

**Issue by ZubairKhan001** [Kaixhin/FCN-semantic-segmentation#8]
please guide me about this error. thanks

**Comment by Kaixhin** [comment]
Sorry for the delay. Are you running the code and utilising the dataset exactly as specified in the README? If you have changed the code (e.g. the network architecture) or are using a different dataset then this error is likely to happen. If this is not the case, please provide the error messages that occur beforehand - there should be references to lines in the code.

**Comment by pharrellyhy** [comment]
Hi @Kaixhin 
If I use a random input just for sanity check, like `torch.empty(1, 3, 96, 96).random_(2)`, the error occurs.

**Comment by Kaixhin** [comment]
I'm confused as to how this broke over time, but I guess it must be something that changed in Torch as I'm now using the latest version. Should be working now.
